D2K/D2K/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls)
]

D2K/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'



urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.SubtitleView.as_view(), name='directory'),
    path('title/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('paragraph/<int:sub_id>/', views.ParagraphView.as_view(), name='paragraph'),

]

D2K/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    #path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

D2K/blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Title(models.Model):
    Title_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.Title_text
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Subtitle(models.Model):
    title = models.ForeignKey(Title, on_delete=models.CASCADE, default = '')
    pub_date = models.DateTimeField('date published')
    context = models.CharField(max_length=200,default = '' )
    def __str__(self):
        return self.context

class Paragraph(models.Model):
    title = models.ForeignKey(Title, on_delete=models.CASCADE, default = '')
    subtitle = models.ForeignKey(Subtitle, on_delete=models.CASCADE, default = '' )
    pub_date = models.DateTimeField('date published')
    context = models.TextField(max_length=5000)
    #Label = models.CharField(max_length=200, default = '')
    def __str__(self):
        return self.context
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

D2K/polls/models.py
from django.db import models
import datetime
from django.utils import timezone


# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

D2K/blog/views.py
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect

from django.shortcuts import get_object_or_404, render
from django.http import Http404

from .models import Paragraph, Title, Subtitle
from django.urls import reverse
from django.views import generic
#def index(request):
#    return HttpResponse("Hello, this is My Blog.")




class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_title_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Title.objects.order_by('-pub_date')



class DetailView(generic.ListView):
    
    template_name = 'blog/detail.html'
    context_object_name = 'latest_subtitle_list'

    @property
    def pk(self):
       return self.kwargs['pk']

    def get_queryset(self):
        print(f"pk = {self.pk}")
        return Subtitle.objects.all().filter(title=self.pk).order_by('-pub_date')



'''
class DetailView(generic.DetailView):
    model = Paragraph
    template_name = 'blog/detail.html'
'''
class ParagraphView(generic.ListView):
    template_name = 'blog/paragraph.html'
    context_object_name = 'latest_paragraph_list'

    @property
    #def pk(self):
    #   return self.kwargs['pk']
    def sub_id(self):
       return self.kwargs['sub_id']
    def get_queryset(self):
        #print(f"pk = {self.pk}")
        print(f"sub_id = {self.sub_id}")
        return Paragraph.objects.all().filter(subtitle=self.sub_id).order_by('-pub_date')

D2K/polls/views.py
from .models import Question, Choice
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import Http404
from django.template import loader
from .models import Choice, Question
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Choice, Question



class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]
'''
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
   }
    return HttpResponse(template.render(context, request))
'''

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
'''    
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
'''

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

'''
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
'''

# ...
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

D2K/blog/templates/blog/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

<div class="header">
    <h1>Gloria' Blog</h1>
    <p>Hand books for bioinformatics, statistics and machine learning</p>
  </div>


<h1>{{ Title.Title_text }}</h1>
<p>{{ Title.Title_text}}</p>

{% for subtitle in latest_subtitle_list %}
    <p> <b> {{subtitle.title}}</b></p> </br>
    <ul> <li><a href="{% url 'blog:paragraph' subtitle.id %}">{{ subtitle.context }}</a></li></ul>
    
    {% endfor %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="footer">
    <p>Copyright @Gloria Contact: gqin@systemsbiology.org</p>
  </div>

D2K/blog/templates/blog/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

<div class="header">
    <h1>Gloria' Blog</h1>
    <p>Hand books for bioinformatics, statistics and machine learning</p>
  </div>

{% if latest_title_list %}
    {% for title in latest_title_list %}
    <ul> <li><a href="{% url 'blog:detail' title.id %}">{{ title.Title_text }}</a></li></ul>
    {% endfor %}

{% else %}
    <p>No posts are available.</p>
{% endif %}

<div class="footer">
    <p>Copyright @Gloria Contact: gqin at systemsbiology.org</p>
  </div>

D2K/blog/templates/blog/paragraph.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
<div class="header">
    <h1>Gloria' Blog</h1>
    <p>Hand books for bioinformatics, statistics and machine learning</p>
  </div>

<h1>{{ Title.Title_text }}</h1>
<p><a>{{ Title.Title_text}}</a></p>

{% for paragraph in latest_paragraph_list %}
    <p> <b> {{paragraph.subtitle}}</b></p> </br>
    <pre> {{ paragraph.context }} </pre>
    
    {% endfor %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="footer">
    <p>Copyright @Gloria Contact: gqin at systemsbiology.org</p>
  </div>

D2K/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul>

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
        </form>

D2K/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

D2K/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>